# service to connect to the app from external network
kind: Service 
apiVersion: v1 
metadata:
  name: frontend-service 
spec:
  type: NodePort
  selector:
    app: webapp 
  ports:
    - port: 8080
      nodePort: 30050
      targetPort: 80
      protocol: TCP
---
# storage class for storage objects
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-web
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Retain
---
# PVC for the PVs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-web
spec:
  storageClassName: sc-web
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi

---
# PV for the nginx container - nginx configuration file.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-conf
spec:
  storageClassName: sc-web
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/Users/almog/Desktop/DevopsApp/nginx.conf"
---
# PV for the nginx container - web files.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-web-files
spec:
  storageClassName: sc-web
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/Users/almog/Desktop/DevopsApp/templates/"
---
# PV for the php container - web files.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-php-web-files
spec:
  storageClassName: sc-web
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/Users/almog/Desktop/DevopsApp/templates/"
---