---
kind: Service 
apiVersion: v1 
metadata:
  name: frontend-service 
spec:
  type: NodePort
  selector:
    app: webapp 
  ports:
    - port: 8888
      nodePort: 30050
      targetPort: 80
      protocol: TCP
---
# PVC for the PVs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-conf
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-web-templates-files
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-php
# spec:
#   storageClassName: ""
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 50Mi
#---
# PV for the nginx container - web files.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-web-templates-files
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/nginx-pod/templates/"
  claimRef:
     namespace: default
     name: pvc-web-templates-files
---
# PV for the nginx container - nginx configuration file.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-conf
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/nginx-pod/nginx-conf/"
  claimRef:
     namespace: default
     name: pvc-nginx-conf
---
# PV for the php container - web files.
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-php-web-files
# spec:
#   storageClassName: ""
#   capacity:
#     storage: 150Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/c/Users/almog/Desktop/DevopsAppOld/templates/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      volumes:
        - name: pv-nginx-conf-volume
          persistentVolumeClaim:
            claimName: pvc-nginx-conf
        - name: pv-nginx-web-templates-files-volume
          persistentVolumeClaim:
            claimName: pvc-web-templates-files
      containers:
        - name: frontend
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pv-nginx-conf-volume
              mountPath: "/etc/nginx/nginx.conf"
              subPath: nginx.conf
            - name: pv-nginx-web-templates-files-volume
              mountPath: "/usr/share/nginx/html/"
              #subPath: html
---